name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env: # Or as an environment variable
        NGROK_AUTHTOKEN: ${{ secrets.NGROKTOKEN  }}
      run: cargo test
